services:
  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pisoftsolutions_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Rails Application
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres:password@db:5432/pisoftsolutions_development
      REDIS_URL: redis://redis:6379/0
      RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID:-rzp_test_1234567890abcdef}
      RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET:-abcdef1234567890abcdef1234567890}
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: rails server -b 0.0.0.0

  # Sidekiq for background jobs (optional)
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres:password@db:5432/pisoftsolutions_development
      REDIS_URL: redis://redis:6379/0
      RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID:-rzp_test_1234567890abcdef}
      RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET:-abcdef1234567890abcdef1234567890}
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: bundle exec sidekiq
    profiles:
      - background

volumes:
  postgres_data:
  redis_data:
  bundle_cache:
